import './css/style.css'

import { Inter, Lobster } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const lobster = Lobster({
  subsets: ['latin'],
  variable: '--font-lobster',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<body className={`${inter.variable} ${lobster.variable} font-inter antialiased bg-white text-slate-800 tracking-tight`}>        {children}
      </body>
    </html>
  )
}
